baseURL = "https://simrankc.com.np"
languageCode = "en-us"
title = "Simran KC"
theme = "PaperMod"
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 30

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience"
weight = 40

[[menu.main]]
identifier = "others"
name = "Others"
url = "/others"
weight = 50


[params]
showToc = true
TocOpen = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideMeta = false
env = "production"
hideDescriptionInList = false
defaultTheme = "light"

  [params.social]
  email = "kcsimran296@gmail.com"
  linkedin = "https://www.linkedin.com/in/simran-kc"
  github = "https://github.com/iamsims"

  [params.profileMode]
  enabled = true
  title = "Simran KC"
  subtitle = "Graduate Research Assistant at NASA IMPACT | Specializing in NLP, Large Language Models, and Backend Development with Python & FastAPI | Building scalable ML systems and human-centric AI agents"
  imageUrl = "home/my-pic.jpg"
  imageWidth = 220
  imageHeight = 220

  [params.cover]
  hiddenInList = false
  hiddenInSingle = false

  [[params.socialIcons]]
  name = "email"
  url = "mailto:kcsimran296@gmail.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/simran-kc"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/iamsims"

  [[params.socialIcons]]
  name = "cv"
  url = "https://drive.google.com/file/d/1pUlW4q67wya4pXry4HY8qF-knjB7dkSG/view?usp=sharing"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true
